import React from "react";

const ProjectDetails = props => {
  const id = props.match.params.id;
  return (
    <div className="container section project-detials">
      <div className="card z-depth-0">
        <div className="card-content">
          <span className="card-title">Project Title -{id}</span>
          <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum imperdiet nibh, nec pulvinar dui dictum at. Pellentesque et posuere mauris. Nulla feugiat enim urna, et interdum sapien interdum in. Sed eu fringilla justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel orci et turpis eleifend consequat. Nulla in rhoncus justo, eu tempor erat. Donec orci purus, imperdiet id felis non, vestibulum ornare dui. Morbi gravida diam massa, non finibus leo egestas a. Nam leo ante, gravida feugiat luctus ut, rhoncus eu justo. Vivamus bibendum lacinia lacinia. Etiam quam magna, accumsan et arcu ac, pharetra feugiat felis. Integer sollicitudin ex vel neque ullamcorper, in molestie mi semper. Phasellus nec diam elit. Duis sed ante a nibh venenatis auctor vel sit amet urna. Duis sapien felis, finibus vel convallis vitae, venenatis ut est.

Morbi sed massa a sem aliquet placerat. Pellentesque quis diam lobortis, fermentum eros vel, venenatis orci. Integer eros ante, tempor vitae velit eget, faucibus dictum nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consectetur augue ante, egestas convallis nulla sodales eget. Donec commodo felis a mi facilisis pretium. Maecenas egestas elementum lectus nec tristique.

Donec laoreet, dolor ut vehicula tincidunt, ex metus egestas lacus, id lobortis velit velit in risus. Aliquam erat volutpat. Morbi vel ex auctor, lacinia nisl a, tempor massa. Suspendisse eget purus augue. Aenean in felis elementum, euismod urna a, imperdiet diam. Donec rutrum magna ut mi tincidunt, vel ultrices turpis tempor. Nullam nibh diam, commodo sit amet cursus ac, eleifend eget nibh. Maecenas varius dolor sit amet nisl feugiat accumsan. Nullam vel suscipit odio. Phasellus vel bibendum sem.

Phasellus fringilla tempus metus, non aliquam metus auctor a. Curabitur efficitur sed leo interdum suscipit. Proin malesuada nec nunc sit amet sollicitudin. Phasellus leo erat, placerat a leo at, ornare rutrum risus. Pellentesque eu quam nisi. Morbi luctus sem non nibh lobortis cursus. Nulla non facilisis erat. Nam vehicula blandit metus, nec gravida metus varius eget. Sed ac quam pellentesque, interdum ligula ut, luctus erat. Donec ultricies sem at sem sollicitudin aliquet. Curabitur eget auctor tortor, a pharetra nisi. Curabitur pellentesque dictum est vitae dictum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum imperdiet nibh, nec pulvinar dui dictum at. Pellentesque et posuere mauris. Nulla feugiat enim urna, et interdum sapien interdum in. Sed eu fringilla justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel orci et turpis eleifend consequat. Nulla in rhoncus justo, eu tempor erat. Donec orci purus, imperdiet id felis non, vestibulum ornare dui. Morbi gravida diam massa, non finibus leo egestas a. Nam leo ante, gravida feugiat luctus ut, rhoncus eu justo. Vivamus bibendum lacinia lacinia. Etiam quam magna, accumsan et arcu ac, pharetra feugiat felis. Integer sollicitudin ex vel neque ullamcorper, in molestie mi semper. Phasellus nec diam elit. Duis sed ante a nibh venenatis auctor vel sit amet urna. Duis sapien felis, finibus vel convallis vitae, venenatis ut est.

Morbi sed massa a sem aliquet placerat. Pellentesque quis diam lobortis, fermentum eros vel, venenatis orci. Integer eros ante, tempor vitae velit eget, faucibus dictum nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consectetur augue ante, egestas convallis nulla sodales eget. Donec commodo felis a mi facilisis pretium. Maecenas egestas elementum lectus nec tristique.

Donec laoreet, dolor ut vehicula tincidunt, ex metus egestas lacus, id lobortis velit velit in risus. Aliquam erat volutpat. Morbi vel ex auctor, lacinia nisl a, tempor massa. Suspendisse eget purus augue. Aenean in felis elementum, euismod urna a, imperdiet diam. Donec rutrum magna ut mi tincidunt, vel ultrices turpis tempor. Nullam nibh diam, commodo sit amet cursus ac, eleifend eget nibh. Maecenas varius dolor sit amet nisl feugiat accumsan. Nullam vel suscipit odio. Phasellus vel bibendum sem.

Phasellus fringilla tempus metus, non aliquam metus auctor a. Curabitur efficitur sed leo interdum suscipit. Proin malesuada nec nunc sit amet sollicitudin. Phasellus leo erat, placerat a leo at, ornare rutrum risus. Pellentesque eu quam nisi. Morbi luctus sem non nibh lobortis cursus. Nulla non facilisis erat. Nam vehicula blandit metus, nec gravida metus varius eget. Sed ac quam pellentesque, interdum ligula ut, luctus erat. Donec ultricies sem at sem sollicitudin aliquet. Curabitur eget auctor tortor, a pharetra nisi. Curabitur pellentesque dictum est vitae dictum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum imperdiet nibh, nec pulvinar dui dictum at. Pellentesque et posuere mauris. Nulla feugiat enim urna, et interdum sapien interdum in. Sed eu fringilla justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel orci et turpis eleifend consequat. Nulla in rhoncus justo, eu tempor erat. Donec orci purus, imperdiet id felis non, vestibulum ornare dui. Morbi gravida diam massa, non finibus leo egestas a. Nam leo ante, gravida feugiat luctus ut, rhoncus eu justo. Vivamus bibendum lacinia lacinia. Etiam quam magna, accumsan et arcu ac, pharetra feugiat felis. Integer sollicitudin ex vel neque ullamcorper, in molestie mi semper. Phasellus nec diam elit. Duis sed ante a nibh venenatis auctor vel sit amet urna. Duis sapien felis, finibus vel convallis vitae, venenatis ut est.

Morbi sed massa a sem aliquet placerat. Pellentesque quis diam lobortis, fermentum eros vel, venenatis orci. Integer eros ante, tempor vitae velit eget, faucibus dictum nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consectetur augue ante, egestas convallis nulla sodales eget. Donec commodo felis a mi facilisis pretium. Maecenas egestas elementum lectus nec tristique.

Donec laoreet, dolor ut vehicula tincidunt, ex metus egestas lacus, id lobortis velit velit in risus. Aliquam erat volutpat. Morbi vel ex auctor, lacinia nisl a, tempor massa. Suspendisse eget purus augue. Aenean in felis elementum, euismod urna a, imperdiet diam. Donec rutrum magna ut mi tincidunt, vel ultrices turpis tempor. Nullam nibh diam, commodo sit amet cursus ac, eleifend eget nibh. Maecenas varius dolor sit amet nisl feugiat accumsan. Nullam vel suscipit odio. Phasellus vel bibendum sem.

Phasellus fringilla tempus metus, non aliquam metus auctor a. Curabitur efficitur sed leo interdum suscipit. Proin malesuada nec nunc sit amet sollicitudin. Phasellus leo erat, placerat a leo at, ornare rutrum risus. Pellentesque eu quam nisi. Morbi luctus sem non nibh lobortis cursus. Nulla non facilisis erat. Nam vehicula blandit metus, nec gravida metus varius eget. Sed ac quam pellentesque, interdum ligula ut, luctus erat. Donec ultricies sem at sem sollicitudin aliquet. Curabitur eget auctor tortor, a pharetra nisi. Curabitur pellentesque dictum est vitae dictum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum imperdiet nibh, nec pulvinar dui dictum at. Pellentesque et posuere mauris. Nulla feugiat enim urna, et interdum sapien interdum in. Sed eu fringilla justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel orci et turpis eleifend consequat. Nulla in rhoncus justo, eu tempor erat. Donec orci purus, imperdiet id felis non, vestibulum ornare dui. Morbi gravida diam massa, non finibus leo egestas a. Nam leo ante, gravida feugiat luctus ut, rhoncus eu justo. Vivamus bibendum lacinia lacinia. Etiam quam magna, accumsan et arcu ac, pharetra feugiat felis. Integer sollicitudin ex vel neque ullamcorper, in molestie mi semper. Phasellus nec diam elit. Duis sed ante a nibh venenatis auctor vel sit amet urna. Duis sapien felis, finibus vel convallis vitae, venenatis ut est.

Morbi sed massa a sem aliquet placerat. Pellentesque quis diam lobortis, fermentum eros vel, venenatis orci. Integer eros ante, tempor vitae velit eget, faucibus dictum nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consectetur augue ante, egestas convallis nulla sodales eget. Donec commodo felis a mi facilisis pretium. Maecenas egestas elementum lectus nec tristique.

Donec laoreet, dolor ut vehicula tincidunt, ex metus egestas lacus, id lobortis velit velit in risus. Aliquam erat volutpat. Morbi vel ex auctor, lacinia nisl a, tempor massa. Suspendisse eget purus augue. Aenean in felis elementum, euismod urna a, imperdiet diam. Donec rutrum magna ut mi tincidunt, vel ultrices turpis tempor. Nullam nibh diam, commodo sit amet cursus ac, eleifend eget nibh. Maecenas varius dolor sit amet nisl feugiat accumsan. Nullam vel suscipit odio. Phasellus vel bibendum sem.

Phasellus fringilla tempus metus, non aliquam metus auctor a. Curabitur efficitur sed leo interdum suscipit. Proin malesuada nec nunc sit amet sollicitudin. Phasellus leo erat, placerat a leo at, ornare rutrum risus. Pellentesque eu quam nisi. Morbi luctus sem non nibh lobortis cursus. Nulla non facilisis erat. Nam vehicula blandit metus, nec gravida metus varius eget. Sed ac quam pellentesque, interdum ligula ut, luctus erat. Donec ultricies sem at sem sollicitudin aliquet. Curabitur eget auctor tortor, a pharetra nisi. Curabitur pellentesque dictum est vitae dictum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum imperdiet nibh, nec pulvinar dui dictum at. Pellentesque et posuere mauris. Nulla feugiat enim urna, et interdum sapien interdum in. Sed eu fringilla justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vel orci et turpis eleifend consequat. Nulla in rhoncus justo, eu tempor erat. Donec orci purus, imperdiet id felis non, vestibulum ornare dui. Morbi gravida diam massa, non finibus leo egestas a. Nam leo ante, gravida feugiat luctus ut, rhoncus eu justo. Vivamus bibendum lacinia lacinia. Etiam quam magna, accumsan et arcu ac, pharetra feugiat felis. Integer sollicitudin ex vel neque ullamcorper, in molestie mi semper. Phasellus nec diam elit. Duis sed ante a nibh venenatis auctor vel sit amet urna. Duis sapien felis, finibus vel convallis vitae, venenatis ut est.

Morbi sed massa a sem aliquet placerat. Pellentesque quis diam lobortis, fermentum eros vel, venenatis orci. Integer eros ante, tempor vitae velit eget, faucibus dictum nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris consectetur augue ante, egestas convallis nulla sodales eget. Donec commodo felis a mi facilisis pretium. Maecenas egestas elementum lectus nec tristique.

Donec laoreet, dolor ut vehicula tincidunt, ex metus egestas lacus, id lobortis velit velit in risus. Aliquam erat volutpat. Morbi vel ex auctor, lacinia nisl a, tempor massa. Suspendisse eget purus augue. Aenean in felis elementum, euismod urna a, imperdiet diam. Donec rutrum magna ut mi tincidunt, vel ultrices turpis tempor. Nullam nibh diam, commodo sit amet cursus ac, eleifend eget nibh. Maecenas varius dolor sit amet nisl feugiat accumsan. Nullam vel suscipit odio. Phasellus vel bibendum sem.

Phasellus fringilla tempus metus, non aliquam metus auctor a. Curabitur efficitur sed leo interdum suscipit. Proin malesuada nec nunc sit amet sollicitudin. Phasellus leo erat, placerat a leo at, ornare rutrum risus. Pellentesque eu quam nisi. Morbi luctus sem non nibh lobortis cursus. Nulla non facilisis erat. Nam vehicula blandit metus, nec gravida metus varius eget. Sed ac quam pellentesque, interdum ligula ut, luctus erat. Donec ultricies sem at sem sollicitudin aliquet. Curabitur eget auctor tortor, a pharetra nisi. Curabitur pellentesque dictum est vitae dictum.

          </p>
          <div className="card-action grey lighten-4 grey-text">
            <div>Posted by Ali</div>
            <div>2nd September,2am</div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default ProjectDetails;
